/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_hops_management_nvidia_NvidiaManagementLibrary */

#ifndef _Included_io_hops_management_nvidia_NvidiaManagementLibrary
#define _Included_io_hops_management_nvidia_NvidiaManagementLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_hops_management_nvidia_NvidiaManagementLibrary
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_hops_management_nvidia_NvidiaManagementLibrary_initialize
  (JNIEnv *, jobject);

/*
 * Class:     io_hops_management_nvidia_NvidiaManagementLibrary
 * Method:    shutDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_hops_management_nvidia_NvidiaManagementLibrary_shutDown
  (JNIEnv *, jobject);

/*
 * Class:     io_hops_management_nvidia_NvidiaManagementLibrary
 * Method:    getNumGPUs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_hops_management_nvidia_NvidiaManagementLibrary_getNumGPUs
  (JNIEnv *, jobject);

/*
 * Class:     io_hops_management_nvidia_NvidiaManagementLibrary
 * Method:    queryMandatoryDevices
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_hops_management_nvidia_NvidiaManagementLibrary_queryMandatoryDevices
  (JNIEnv *, jobject);

/*
 * Class:     io_hops_management_nvidia_NvidiaManagementLibrary
 * Method:    queryAvailableDevices
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_hops_management_nvidia_NvidiaManagementLibrary_queryAvailableDevices
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif