/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NvidiaManagementLibrary */

#ifndef _Included_NvidiaManagementLibrary
#define _Included_NvidiaManagementLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NvidiaManagementLibrary
 * Method:    queryMandatoryDevices
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_apache_hadoop_yarn_server_nodemanager_util_devices_NvidiaManagementLibrary_queryMandatoryDevices
  (JNIEnv *, jobject);

/*
 * Class:     NvidiaManagementLibrary
 * Method:    queryAvailableDevices
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_apache_hadoop_yarn_server_nodemanager_util_devices_NvidiaManagementLibrary_queryAvailableDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
